"""
Export Service - Generate reports in various formats.
"""

import json
import logging
from typing import Optional
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.models.graph import Repository, GraphFile, Symbol, Edge
from app.models.version import RepoVersion
from app.services.scanner import ScannerService
from app.services.graph_service import GraphService

logger = logging.getLogger("export_service")


class ExportService:
    @staticmethod
    async def export(
        scan_id: str,
        format: str,
        include_graph: bool,
        include_health: bool,
        include_hotspots: bool,
        db: AsyncSession,
    ) -> str:
        """
        Export repository analysis in the specified format.
        """
        # Get scan data
        if scan_id not in ScannerService.SCANS:
            raise ValueError("Scan not found")

        scan = ScannerService.SCANS[scan_id]

        # Collect data
        data = {
            "scan_id": scan_id,
            "status": scan.status,
            "stats": scan.stats.model_dump() if scan.stats else None,
        }

        # Add health data
        if include_health and scan_id in ScannerService.HEALTH_DATA:
            health = ScannerService.HEALTH_DATA[scan_id]
            data["health"] = {
                "risk_score": health.riskScore,
                "circular_dependencies": health.circularDependencies,
                "complexity_score": health.complexityScore,
            }

            if include_hotspots:
                data["hotspots"] = [
                    {"file": h.file, "score": h.score}
                    for h in health.hotspots
                ]

        # Add graph data
        if include_graph:
            try:
                graph = await GraphService.get_graph(scan_id, db)
                data["graph"] = {
                    "total_files": graph.total_files,
                    "total_symbols": graph.total_symbols,
                    "total_edges": graph.total_edges,
                    "circular_dependencies": [
                        {"cycle": c.cycle, "type": c.type}
                        for c in graph.circular_dependencies
                    ],
                }
            except Exception as e:
                logger.warning(f"Failed to load graph data: {e}")
                data["graph"] = None

        # Format output
        if format == "json":
            return json.dumps(data, indent=2)

        elif format == "markdown":
            return ExportService._format_markdown(data)

        else:  # html
            return ExportService._format_html(data)

    @staticmethod
    def _format_markdown(data: dict) -> str:
        """Generate Markdown report."""
        md = f"""# CodeFlux Analysis Report

**Scan ID:** `{data['scan_id']}`
**Status:** {data['status']}
**Generated:** {ExportService._get_timestamp()}

---

## Repository Statistics

"""
        if data.get('stats'):
            stats = data['stats']
            md += f"""- **Files:** {stats.get('files', 0)}
- **Symbols:** {stats.get('symbols', 0)}
- **Dependencies:** {stats.get('dependencies', 0)}

"""

        if data.get('health'):
            health = data['health']
            md += f"""---

## Health Metrics

- **Risk Score:** {health['risk_score']}/100
- **Circular Dependencies:** {health['circular_dependencies']}
- **Complexity Score:** {health['complexity_score']}

"""

        if data.get('hotspots'):
            md += """---

## Complexity Hotspots

| File | Complexity Score |
|------|------------------|
"""
            for h in data['hotspots'][:10]:
                md += f"| `{h['file']}` | {h['score']:.1f} |\n"

        if data.get('graph'):
            graph = data['graph']
            md += f"""---

## Code Graph

- **Total Files:** {graph['total_files']}
- **Total Symbols:** {graph['total_symbols']}
- **Total Edges:** {graph['total_edges']}
- **Circular Dependencies:** {len(graph['circular_dependencies'])}

"""

        md += """---

*Generated by [CodeFlux](https://github.com/yourusername/codeflux) - AI-Powered Code Analysis Platform*
"""
        return md

    @staticmethod
    def _format_html(data: dict) -> str:
        """Generate HTML report."""
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CodeFlux Analysis Report</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem;
            background: #0f172a;
            color: #e2e8f0;
        }}
        h1, h2 {{ color: #818cf8; }}
        .card {{
            background: #1e293b;
            border: 1px solid #334155;
            border-radius: 8px;
            padding: 1.5rem;
            margin-bottom: 1.5rem;
        }}
        .stat {{
            display: inline-block;
            margin-right: 2rem;
            margin-bottom: 1rem;
        }}
        .stat-label {{
            color: #94a3b8;
            font-size: 0.875rem;
            text-transform: uppercase;
        }}
        .stat-value {{
            font-size: 2rem;
            font-weight: bold;
            color: #818cf8;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 1rem;
        }}
        th, td {{
            padding: 0.75rem;
            text-align: left;
            border-bottom: 1px solid #334155;
        }}
        th {{
            background: #334155;
            color: #818cf8;
            font-weight: 600;
        }}
        code {{
            background: #0f172a;
            padding: 0.2rem 0.4rem;
            border-radius: 4px;
            font-family: 'Courier New', monospace;
        }}
        .footer {{
            text-align: center;
            margin-top: 3rem;
            color: #64748b;
            font-size: 0.875rem;
        }}
    </style>
</head>
<body>
    <h1>CodeFlux Analysis Report</h1>
    <div class="card">
        <p><strong>Scan ID:</strong> <code>{data['scan_id']}</code></p>
        <p><strong>Status:</strong> {data['status']}</p>
        <p><strong>Generated:</strong> {ExportService._get_timestamp()}</p>
    </div>
"""

        if data.get('stats'):
            stats = data['stats']
            html += f"""
    <div class="card">
        <h2>Repository Statistics</h2>
        <div class="stat">
            <div class="stat-label">Files</div>
            <div class="stat-value">{stats.get('files', 0)}</div>
        </div>
        <div class="stat">
            <div class="stat-label">Symbols</div>
            <div class="stat-value">{stats.get('symbols', 0)}</div>
        </div>
        <div class="stat">
            <div class="stat-label">Dependencies</div>
            <div class="stat-value">{stats.get('dependencies', 0)}</div>
        </div>
    </div>
"""

        if data.get('health'):
            health = data['health']
            html += f"""
    <div class="card">
        <h2>Health Metrics</h2>
        <div class="stat">
            <div class="stat-label">Risk Score</div>
            <div class="stat-value">{health['risk_score']}/100</div>
        </div>
        <div class="stat">
            <div class="stat-label">Circular Dependencies</div>
            <div class="stat-value">{health['circular_dependencies']}</div>
        </div>
        <div class="stat">
            <div class="stat-label">Complexity Score</div>
            <div class="stat-value">{health['complexity_score']}</div>
        </div>
    </div>
"""

        if data.get('hotspots'):
            html += """
    <div class="card">
        <h2>Complexity Hotspots</h2>
        <table>
            <thead>
                <tr>
                    <th>File</th>
                    <th>Complexity Score</th>
                </tr>
            </thead>
            <tbody>
"""
            for h in data['hotspots'][:10]:
                html += f"""
                <tr>
                    <td><code>{h['file']}</code></td>
                    <td>{h['score']:.1f}</td>
                </tr>
"""
            html += """
            </tbody>
        </table>
    </div>
"""

        if data.get('graph'):
            graph = data['graph']
            html += f"""
    <div class="card">
        <h2>Code Graph</h2>
        <div class="stat">
            <div class="stat-label">Total Files</div>
            <div class="stat-value">{graph['total_files']}</div>
        </div>
        <div class="stat">
            <div class="stat-label">Total Symbols</div>
            <div class="stat-value">{graph['total_symbols']}</div>
        </div>
        <div class="stat">
            <div class="stat-label">Total Edges</div>
            <div class="stat-value">{graph['total_edges']}</div>
        </div>
        <div class="stat">
            <div class="stat-label">Circular Dependencies</div>
            <div class="stat-value">{len(graph['circular_dependencies'])}</div>
        </div>
    </div>
"""

        html += """
    <div class="footer">
        Generated by <strong>CodeFlux</strong> - AI-Powered Code Analysis Platform
    </div>
</body>
</html>
"""
        return html

    @staticmethod
    def _get_timestamp() -> str:
        """Get current timestamp."""
        from datetime import datetime
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
